### ISSUE TITLE
client.big_data_pools.update for "Update a Big Data pool" does not work

### ISSUE THREAD

**Issue by thinkORo** [Azure/azure-rest-api-specs-examples#1648]
### Library name and version

from azure.mgmt.synapse import SynapseManagementClient

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [X] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [X] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

    respone = client.big_data_pools.update(
        resource_group_name=azure_resource_group_name,  # "rg-res895793475",
        workspace_name=azure_workspace_name,            # "synrgres0013594875937",
        big_data_pool_name=azure_big_data_pool_name,    # "synspsmall8787",
        big_data_pool_patch_info={
            "properties": {
                "AutoScaleProperties": {
                    "enabled": True,
                    "maxNodeCount": 3,
                    "minNodeCount" : 5
                }
            }
        }
    )

### Expected behavior

The auto-scale value should switch from false to true and the max parameter should be 5

### Actual behavior

auto-scale is still false and max nodes is still 3

### Environment

Python 3.10.8 and latest Azure Python Frameworks

from azure.identity import DefaultAzureCredential
from azure.mgmt.synapse import SynapseManagementClient

**Comment by Wzb123456789** [comment]
@thinkORo 

Thanks for your feedback, , the usage of this service has been updated.
You can try the following methods to solve your problem:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/synapse/azure-mgmt-synapse/generated_samples/update_big_data_pool.py
