### ISSUE TITLE
Filter data based on usage_date

### ISSUE THREAD

**Issue by anurag8899** [Azure/azure-rest-api-specs-examples#1676]
### Link to sample

https://learn.microsoft.com/en-us/rest/api/cost-management/benefit-utilization-summaries/list-by-billing-account-id?tabs=Python

### Library name and version

savingsplan utilization data

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [X] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [ ] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

How can I filter savingsplan utilization based on usage_date in python. so that i can extract data for a month everytime.

**Comment by anurag8899** [comment]
i am using below code:  client = CostManagementClient(
        credential=DefaultAzureCredential(),
    )

    response = client.benefit_utilization_summaries.list_by_billing_account_id(
        billing_account_id="12345",
    )

**Comment by msyyc** [comment]
Hi @anurag8899 I find a [sample](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2022-10-01/examples/BenefitUtilizationSummaries/SavingsPlan-BillingAccount.json) about how to use "filter". And you can try:
```
response = client.benefit_utilization_summaries.list_by_billing_account_id(
    billing_account_id="12345",
    filter="properties/usageDate ge 2022-10-15 and properties/usageDate le 2022-10-18",
)
```
