### ISSUE TITLE
sentinel_onboarding_states.create() fails with HTTPResponse Error - Bad Request

### ISSUE THREAD

**Issue by caseymullineaux** [Azure/azure-rest-api-specs-examples#1935]
### Link to sample

https://learn.microsoft.com/en-us/rest/api/securityinsights/preview/sentinel-onboarding-states/create?tabs=Python

### Library name and version

azure-mgmt-securityinsight v1.0.0

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [X] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [X] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

Using the sample python code in the documentation to create a Microsoft Sentinel onboarding state on an existing workspace fails with a `HTTPResponseError - Bad request`. It seems to suggests a required property is missing from the request.

### Expected behavior

An onboarding state is created on the workspace for Microsoft Sentinel

### Actual behavior

**Error returned**
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/casey/source/sandbox/python-azure/.venv/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/casey/source/sandbox/python-azure/.venv/lib/python3.9/site-packages/azure/mgmt/securityinsight/operations/_sentinel_onboarding_states_operations.py", line 344, in create
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (BadRequest) A non-empty request body is required.
Code: BadRequest
Message: A non-empty request body is required.
```

### Reproduction Steps

1. Install dependencies:
- `pip install azure-mgmt-securityinsight azure-identity`
2. Execute sample code

### Environment

- Macbook Air M1 running MacOS Ventura 13.1
- Python: 3.9.6

```bash
> pip show azure-mgmt-securityinsight
Name: azure-mgmt-securityinsight
Version: 1.0.0
Summary: Microsoft Azure Security Insight Management Client Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: /Users/casey/.pyenv/versions/3.10.2/lib/python3.10/site-packages
Requires: azure-common, azure-mgmt-core, msrest
Required-by: 
```

```bash
> pip show azure-identity
Name: azure-identity
Version: 1.12.0
Summary: Microsoft Azure Identity Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/identity/azure-identity
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: /Users/casey/.pyenv/versions/3.10.2/lib/python3.10/site-packages
Requires: azure-core, cryptography, msal, msal-extensions, six
Required-by: 
```

**Comment by xboxeer** [comment]
@msyyc would you help check?

**Comment by msyyc** [comment]
The issue is releated with https://github.com/Azure/azure-rest-api-specs/issues/22729. Please try the following code:
```python
...
response = client.sentinel_onboarding_states.create(
    resource_group_name="myRg",
    workspace_name="myWorkspace",
    sentinel_onboarding_state_name="default",
    sentinel_onboarding_state_parameter={
        "properties": {
            "customerManagedKey": False
        }
    }
)

...
```

**Comment by caseymullineaux** [comment]
Can confirm this code works ☝️

**Comment by caseymullineaux** [comment]
We're not going to update the example code on the doc? The next person that tries to use it is going to have the same problem.

**Comment by xboxeer** [comment]
> We're not going to update the example code on the doc? The next person that tries to use it is going to have the same problem.

These examples are generated from service team defined swagger sample, we've opened issue to service team and need them to fix their swagger issue.
