### ISSUE TITLE
Keyvault latest version 1.1.0 does not support secrets. 

### ISSUE THREAD

**Issue by shpriyams** [Azure/azure-rest-api-specs-examples#2165]
### Library name and version

Azure.ResourceManager.Keyvault

### Language of the Sample

- [X] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [ ] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [X] Sample not working
- [X] Sample missing
- [ ] Do not understand sample

### Issue details

We are migrating from **Microsoft.Azure.Management.KeyVault** SDK to the new **Azure.ResourceManager.KeyVault** SDK (latest 1.1.0)

1. We noticed that the latest version did not contain Secret resource or any capability to support secrets. No example found for the same.
2. We downgraded the version to 1.0.0.-beta8. Even though it supports SecretResource, we are unable to fetch any secrets in the code. The value remains null.

Please provide examples or guidance to fetch Secret resource.

### Environment

development

**Comment by xboxeer** [comment]
@ArcturusZhang @ArthurMa1978 can you help check?

**Comment by dvbb** [comment]
We removed the preview API when we released the stable version, now that we have a stable version of the KeyVault secrets, we will bump the API version and add this feature back in the next `Azure.ResourceManager.KeyVault` version

**Comment by shpriyams** [comment]
Thank you for responding. The stable version does not support keyvault secrets, could you help us understand if there's something we are missing.

**Comment by dvbb** [comment]
> The stable version does not support keyvault secrets

Yes, our current `Azure.ResourceManager.KeyVaultsdk` 1.1.0 version does not support `Secrets` operations, but we will release a new version to support that this month(March 2023)
