### ISSUE TITLE
[Sample Issue]

### ISSUE THREAD

**Issue by YeisonCaballero1993** [Azure/azure-rest-api-specs-examples#2168]
### Link to sample

sdfa

### Library name and version

22

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [X] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [ ] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

aoa

**Comment by msyyc** [comment]
Hi @YeisonCaballero1993 Could you share more detailed info about the issue?
