### ISSUE TITLE
List users for a static site is giving an permission error

### ISSUE THREAD

**Issue by Petri-Leinonen** [Azure/azure-rest-api-specs-examples#2188]
### Library name and version

"@azure/arm-appservice": "^13.0.3" and "@azure/identity": "^3.1.3"

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [X] JavaScript/TypedScript
- [ ] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [X] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

I'm trying to get this sample code to work in my Static Web App function: https://learn.microsoft.com/en-us/rest/api/appservice/static-sites/list-static-site-users?tabs=JavaScript

It seems to respond correctly, but instead of giving the list of users it gives me two different errors:
- AggregateAuthenticationError
- CredentialUnavailableError

What am I missing here? I can run the code just fine locally and get a list of users. But when I deploy my app I'm getting these errors.

### Expected behavior

Get a list of static web app users.

### Actual behavior

Getting an error messages:

- AggregateAuthenticationError
- CredentialUnavailableError

### Reproduction Steps

Just copy paste the code in example, deploy it and try to run it.

**Comment by MaryGao** [comment]
@kazrael2119 Could you take a look at this issue?

**Comment by kazrael2119** [comment]
@Petri-Leinonen could give more details about this?
> What am I missing here? I can run the code just fine locally and get a list of users. But when I deploy my app I'm getting these errors.

**Comment by kazrael2119** [comment]
close this issue as there has been no response for a long time. please create a new issue if necessary. Thanks
