### ISSUE TITLE
[Sample Issue]

### ISSUE THREAD

**Issue by ahsanj** [Azure/azure-rest-api-specs-examples#2485]
### Link to sample

https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-subscription_3.2.0b1/sdk/subscription/azure-mgmt-subscription/generated_samples/rename_subscription.py

### Library name and version

azure-mgmt-subscription

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [X] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [ ] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-subscription_3.2.0b1/sdk/subscription/azure-mgmt-subscription/generated_samples/rename_subscription.py

subscription.**rename** is not present

**Comment by msyyc** [comment]
Hi, it shall be here: https://github.com/Azure/azure-sdk-for-python/blob/14a128f7529a64c1eda3f34881d5096480c3608c/sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/_subscription_operations.py#L292-L307
