### ISSUE TITLE
[Sample Issue]

### ISSUE THREAD

**Issue by Vinaykumargowda** [Azure/azure-rest-api-specs-examples#2486]
### Link to sample

https://learn.microsoft.com/en-us/rest/api/virtualnetwork/network-security-groups/list?tabs=Python&tryIt=true&source=docs#code-try-0

### Library name and version

Python 3.7+ . https://aka.ms/azsdk/python/all

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [X] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [ ] Sample not working
- [ ] Sample missing
- [X] Do not understand sample

### Issue details

Python is output is not expected. it's not in Json format.  getting in below format - 

{'additional_properties': {}, 'id': '/subscriptions/xxxxxxxxx-xxxx-xxxxx-xxxx-xxxxxxxx/resourceGroups/xx-xxxx-xxx/providers/Microsoft.Network/networkSecurityGroups/xxxxx-nsg', 'name': 'xxxxxx-nsg', 'type': 'Microsoft.Network/networkSecurityGroups', 'location': 'CentralUS', 'tags': None, 'etag': 'W/"xxxxx-5a47-xxxxx-a6da-xxxxxxx"', 'flush_connection': None, 'security_rules': [<azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C2890>, <azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C2A10>, <azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C2B90>, <azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C2D10>, <azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C2E90>, <azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C3050>, <azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C31D0>, <azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C3350>, <azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C34D0>], 'default_security_rules': [<azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C3650>, <azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C37D0>, <azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C3950>, <azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C3AD0>, <azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C3C50>, <azure.mgmt.network.models._models.SecurityRule object at 0x000001DC2D4C3E10>], 'network_interfaces': None, 'subnets': None, 'flow_logs': [<azure.mgmt.network.models._models.FlowLog object at 0x000001DC2D4C3ED0>], 'resource_guid': 'xxxx4308-xxxx-40b5-xxxx-af9652xxxxxx', 'provisioning_state': 'Succeeded'}

### Expected behavior

it should be in Json Format - refer sample response for python.

https://learn.microsoft.com/en-us/rest/api/virtualnetwork/network-security-groups/list?tabs=Python&tryIt=true&source=docs#code-try-0

**Comment by Vinaykumargowda** [comment]
Hi - Any update.?

**Comment by msyyc** [comment]
Hi, please try:
```python
    for item in response:
        print(item.serialize())
```

**Comment by Vinaykumargowda** [comment]
Thanks for your support. Its coming in JSON format
