### ISSUE TITLE
[Sample Issue] Python code not showing

### ISSUE THREAD

**Issue by ReynardoW** [Azure/azure-rest-api-specs-examples#2526]
### Link to sample

https://learn.microsoft.com/en-us/rest/api/azureml/2022-10-01/compute/create-or-update?tabs=Python&source=docs#update-a-aml-compute

### Library name and version

Compute - Create Or Update API-Version: 2022-10-01

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [X] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [X] Sample not working
- [X] Sample missing
- [ ] Do not understand sample

### Issue details

Does not show

**Comment by msyyc** [comment]
will release new version after https://github.com/Azure/autorest.python/issues/1875 fixed

**Comment by msyyc** [comment]
https://pypi.org/project/azure-mgmt-machinelearningservices/2.0.0b2/
