### ISSUE TITLE
unable to connect to postgres flexible server 

### ISSUE THREAD

**Issue by Naveen418** [Azure/azure-rest-api-specs-examples#3020]
### Link to sample

https://learn.microsoft.com/en-us/rest/api/postgresql/flexibleserver/servers/restart?tabs=Python

### Library name and version

azure.mgmt.rdbms

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [X] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [X] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

cannot import name 'PostgreSQLManagementClient' from 'azure.mgmt.rdbms'

### Expected behavior

it should import the package 

### Actual behavior

cannot import name 'PostgreSQLManagementClient' from 'azure.mgmt.rdbms'

### Environment

linux

**Comment by msyyc** [comment]
Please try:
```
from azure.mgmt.rdbms.postgresql_flexibleservers import PostgreSQLManagementClient
```

**Comment by Naveen418** [comment]
> Please try:
> 
> ```
> from azure.mgmt.rdbms.postgresql_flexibleservers import PostgreSQLManagementClient
> ```

Thank you, its worked
