### ISSUE TITLE
[Sample Issue] It appears the example Python script is not working

### ISSUE THREAD

**Issue by robertspears** [Azure/azure-rest-api-specs-examples#3217]
### Library name and version

Python

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [X] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [X] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

The script provided on this page (https://learn.microsoft.com/en-us/rest/api/trafficmanager/endpoints/update?tabs=Python) for Python is not working.  It was tested by a customer and not successful.  The customer provided a sample of code that is working for them.  

`from  azure.identity  import DefaultAzureCredential 
from  azure.mgmt.trafficmanagerimport  TrafficManagerManagementClient 
 
 
def  update_tm_endpoint(target: str):
subscription_id = "subscription_id" 
    resource_group_name = "rg-name" 
    profile_name = "trafficmanager-profile-name" 
    endpoint_type = "azureEndpoints" 
    endpoint_name = "trafficmanagerendpointname" 
    target = "/subscriptions/subscription_id/resourceGroups/rg-name/providers/Microsoft.Web/sites/website-name" 
    weight = "1" 
    endpoint_status = "Enabled" 
    credentials = DefaultAzureCredential()
    traffic_manager_client = TrafficManagerManagementClient(
        credentials, subscription_id 
    )
    endpoint = traffic_manager_client.endpoints.get(
        resource_group_name, profile_name, endpoint_type, endpoint_name 
    )
    endpoint.target_resource_id = target 
    endpoint.weight = weight 
    endpoint.endpoint_status = endpoint_status 
    res = traffic_manager_client.endpoints.create_or_update(
        resource_group_name, profile_name, endpoint_type, endpoint_name, endpoint 
    )
    return  res, datetime.now()`

**Comment by msyyc** [comment]
```python
from azure.identity import DefaultAzureCredential
from azure.mgmt.trafficmanager import TrafficManagerManagementClient

def update_tm_endpoint(target: str):
    subscription_id = "subscription_id"
    resource_group_name = "rg-name"
    profile_name = "trafficmanager-profile-name"
    endpoint_type = "azureEndpoints"
    endpoint_name = "trafficmanagerendpointname"
    target = "/subscriptions/subscription_id/resourceGroups/rg-name/providers/Microsoft.Web/sites/website-name"
    weight = "1"
    endpoint_status = "Enabled"
    credentials = DefaultAzureCredential()
    traffic_manager_client = TrafficManagerManagementClient(
        credentials, subscription_id
    )
    endpoint = traffic_manager_client.endpoints.get(
        resource_group_name, profile_name, endpoint_type, endpoint_name
    )
    endpoint.target_resource_id = target
    endpoint.weight = weight
    endpoint.endpoint_status = endpoint_status
    res = traffic_manager_client.endpoints.create_or_update(
        resource_group_name, profile_name, endpoint_type, endpoint_name, endpoint
    )
    return res, datetime.now()
```

**Comment by robertspears** [comment]
Hi @msyyc .  Thanks for the response and update!
I have to admit that I do not have the ability to personally test the code submission and am relying upon the information provided by them.  At the heart of the customer's ask is that the Python code provided in the documentation does not work.  This led to them writing their own method (which may have its own bugs).  So we don't need to necessarily need to use the customer's code as-is, or in general.

Are you able to tell if there are any errors in the method from the docs?

**Comment by msyyc** [comment]
Hi @robertspears Could you suggest customer to open issue in https://github.com/Azure/azure-sdk-for-python/issues ? If they can provide detailed context, SDK team will try to provide solution.

**Comment by robertspears** [comment]
Hi @msyyc .  I checked - what I earlier sent was the result of after the customer opened a support case.  The case already closed.  After reviewing the notes, it looks to me that there is confusion in what was trying to be accomplished and some of syntax.  Thanks for pointing out the bug.

So just to wrap up, may I confirm you're not seeing errors on the current code on this page?

**Comment by msyyc** [comment]
Yeah.
