### ISSUE TITLE
Invalid URI: The format of the URI could not be determined

### ISSUE THREAD

**Issue by musukwamoshi** [Azure/azure-rest-api-specs-examples#3219]
### Link to sample

https://learn.microsoft.com/en-us/rest/api/datafactory/integration-runtimes/get-status?tabs=dotnet&tryIt=true&source=docs#code-try-0

### Library name and version

Azure.ResourceManager.DataFactory 1.0.0-beta.2

### Language of the Sample

- [X] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [ ] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [ ] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

The issue arises when I try to query the status of  an integration runtime in azure data factory. See link for the code sample used.
The offending line of code seems to be
`IntegrationRuntimeStatusResult result = await factoryIntegrationRuntime.GetStatusAsync();`

I used an azure function to test the code and deployed the function to azure

### Expected behavior

The code sample returns  the status of the specified integration runtime without throwing an error.

### Actual behavior

The code sample  throws an error. See error below

Invalid URI: The format of the URI could not be determined.    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Azure.ResourceManager.DataFactory.Models.SelfHostedIntegrationRuntimeStatus.DeserializeSelfHostedIntegrationRuntimeStatus(JsonElement element)
   at Azure.ResourceManager.DataFactory.Models.IntegrationRuntimeStatus.DeserializeIntegrationRuntimeStatus(JsonElement element)
   at Azure.ResourceManager.DataFactory.Models.IntegrationRuntimeStatusResult.DeserializeIntegrationRuntimeStatusResult(JsonElement element)
   at Azure.ResourceManager.DataFactory.IntegrationRuntimesRestOperations.GetStatusAsync(String subscriptionId, String resourceGroupName, String factoryName, String integrationRuntimeName, CancellationToken cancellationToken)
   at Azure.ResourceManager.DataFactory.FactoryIntegrationRuntimeResource.GetStatusAsync(CancellationToken cancellationToken)

### Reproduction Steps

Replace  code sample variables with valid  subscriptionId ,resourceGroupName ,factoryName  and integrationRuntimeName .
Run the code sample to retrieve  the integration runtime status.

### Environment

Deployed to a function app using windows
IDE Visual Studio 17.0

**Comment by live1206** [comment]
@musukwamoshi It seems like the responded uri is invalid.
Could you help to provide the value of `serviceUrls` from the service response? Thanks!

**Comment by musukwamoshi** [comment]
@live1206  Do you mean the host service uri available through the FactoryIntegrationRuntimeResource object via the GetConnectionInfo() methods? because thats the only uri value I would be able to give you. Thanks

**Comment by live1206** [comment]
@musukwamoshi Sorry for the confusion.
I meant [serviceUrls](https://github.com/Azure/azure-sdk-for-net/blob/17d68f9b0f94cae1e2976523c03b88cc834f145a/sdk/datafactory/Azure.ResourceManager.DataFactory/src/Generated/Models/SelfHostedIntegrationRuntimeStatus.Serialization.cs#L161), and the original operation is [DataFactoryIntegrationRuntimeResource.GetStatusAsync](https://github.com/Azure/azure-sdk-for-net/blob/17d68f9b0f94cae1e2976523c03b88cc834f145a/sdk/datafactory/Azure.ResourceManager.DataFactory/src/Generated/DataFactoryIntegrationRuntimeResource.cs#L314), based on the stack trace you provided.
Please note that the type name is slightly different since it is still beta version.

**Comment by musukwamoshi** [comment]
@live1206  Sorry for the delay but the code sample throws  an exception as a result of  the operation [DataFactoryIntegrationRuntimeResource.GetStatusAsync](https://github.com/Azure/azure-sdk-for-net/blob/17d68f9b0f94cae1e2976523c03b88cc834f145a/sdk/datafactory/Azure.ResourceManager.DataFactory/src/Generated/DataFactoryIntegrationRuntimeResource.cs#L314)  So I cant use the result to check for the serviceUrls

**Comment by live1206** [comment]
@musukwamoshi 
I was expecting you to check the serviceUrls in the raw response since the deserialization failed.
There are a few different ways to get it:
- SDK enabled [sourcelink](https://github.com/Azure/azure-sdk-for-net/blob/b2d4b7f1ecae7c10dede76d3f3b30d42e39907db/eng/Directory.Build.Common.targets#L126), you should be able to debug into the Azure.ResourceManager.DataFactory, set a break point [here](https://github.com/Azure/azure-sdk-for-net/blob/b2d4b7f1ecae7c10dede76d3f3b30d42e39907db/sdk/datafactory/Azure.ResourceManager.DataFactory/src/Generated/RestOperations/IntegrationRuntimesRestOperations.cs#L526) to check the raw response via `message.Response.Content`.
- Make a http request with raw HttpClient, like [this](https://github.com/Azure/azure-sdk-for-net/issues/36876#issuecomment-1640492796)
- Use fiddler to get the http traffic

Since you have the failing scenario in place, it would be great if you can help to get the data for us to make a proper fix. Thanks!

**Comment by musukwamoshi** [comment]
@live1206 Thanks that was helpful. I used the raw httpclient approach. By the way with this approach I was able to check the status without issue. See below for the service urls
`"serviceUrls": [
        "oc-datafactorybi.centralus.datafactory.azure.net",
        "amsprodcu-12.servicebus.windows.net",
        "g0-prod-dm2-011-sb.servicebus.windows.net",
        "g1-prod-dm2-011-sb.servicebus.windows.net",
        "g2-prod-dm2-011-sb.servicebus.windows.net",
        "g3-prod-dm2-011-sb.servicebus.windows.net",
        "g4-prod-dm2-011-sb.servicebus.windows.net",
        "g5-prod-dm2-011-sb.servicebus.windows.net",
        "g6-prod-dm2-011-sb.servicebus.windows.net",
        "g7-prod-dm2-011-sb.servicebus.windows.net",
        "g8-prod-dm2-011-sb.servicebus.windows.net",
        "g9-prod-dm2-011-sb.servicebus.windows.net",
        "g10-prod-dm2-011-sb.servicebus.windows.net",
        "g11-prod-dm2-011-sb.servicebus.windows.net",
        "g12-prod-dm2-011-sb.servicebus.windows.net",
        "g13-prod-dm2-011-sb.servicebus.windows.net",
        "g14-prod-dm2-011-sb.servicebus.windows.net",
        "g15-prod-dm2-011-sb.servicebus.windows.net",
        "g16-prod-dm2-011-sb.servicebus.windows.net",
        "g17-prod-dm2-011-sb.servicebus.windows.net",
        "g18-prod-dm2-011-sb.servicebus.windows.net",
        "g19-prod-dm2-011-sb.servicebus.windows.net",
        "g20-prod-dm2-011-sb.servicebus.windows.net",
        "g21-prod-dm2-011-sb.servicebus.windows.net",
        "g22-prod-dm2-011-sb.servicebus.windows.net",
        "g23-prod-dm2-011-sb.servicebus.windows.net",
        "g24-prod-dm2-011-sb.servicebus.windows.net",
        "g25-prod-dm2-011-sb.servicebus.windows.net",
        "g26-prod-dm2-011-sb.servicebus.windows.net",
        "g27-prod-dm2-011-sb.servicebus.windows.net",
        "g28-prod-dm2-011-sb.servicebus.windows.net",
        "g29-prod-dm2-011-sb.servicebus.windows.net",
        "g30-prod-dm2-011-sb.servicebus.windows.net",
        "g31-prod-dm2-011-sb.servicebus.windows.net",
        "g32-prod-dm2-011-sb.servicebus.windows.net",
        "g33-prod-dm2-011-sb.servicebus.windows.net",
        "g34-prod-dm2-011-sb.servicebus.windows.net",
        "g35-prod-dm2-011-sb.servicebus.windows.net",
        "g36-prod-dm2-011-sb.servicebus.windows.net",
        "g37-prod-dm2-011-sb.servicebus.windows.net",
        "g38-prod-dm2-011-sb.servicebus.windows.net",
        "g39-prod-dm2-011-sb.servicebus.windows.net",
        "g40-prod-dm2-011-sb.servicebus.windows.net",
        "g41-prod-dm2-011-sb.servicebus.windows.net",
        "g42-prod-dm2-011-sb.servicebus.windows.net",
        "g43-prod-dm2-011-sb.servicebus.windows.net",
        "g44-prod-dm2-011-sb.servicebus.windows.net",
        "g45-prod-dm2-011-sb.servicebus.windows.net",
        "g46-prod-dm2-011-sb.servicebus.windows.net",
        "g47-prod-dm2-011-sb.servicebus.windows.net",
        "g48-prod-dm2-011-sb.servicebus.windows.net",
        "g49-prod-dm2-011-sb.servicebus.windows.net",
        "g50-prod-dm2-011-sb.servicebus.windows.net",
        "g51-prod-dm2-011-sb.servicebus.windows.net",
        "g52-prod-dm2-011-sb.servicebus.windows.net",
        "g53-prod-dm2-011-sb.servicebus.windows.net",
        "g54-prod-dm2-011-sb.servicebus.windows.net",
        "g55-prod-dm2-011-sb.servicebus.windows.net",
        "g56-prod-dm2-011-sb.servicebus.windows.net",
        "g57-prod-dm2-011-sb.servicebus.windows.net",
        "g58-prod-dm2-011-sb.servicebus.windows.net",
        "g59-prod-dm2-011-sb.servicebus.windows.net",
        "g60-prod-dm2-011-sb.servicebus.windows.net",
        "g61-prod-dm2-011-sb.servicebus.windows.net",
        "g62-prod-dm2-011-sb.servicebus.windows.net",
        "g63-prod-dm2-011-sb.servicebus.windows.net",
        "g64-prod-dm2-011-sb.servicebus.windows.net",
        "g65-prod-dm2-011-sb.servicebus.windows.net",
        "g66-prod-dm2-011-sb.servicebus.windows.net",
        "g67-prod-dm2-011-sb.servicebus.windows.net",
        "g68-prod-dm2-011-sb.servicebus.windows.net",
        "g69-prod-dm2-011-sb.servicebus.windows.net",
        "g70-prod-dm2-011-sb.servicebus.windows.net",
        "g71-prod-dm2-011-sb.servicebus.windows.net",
        "g72-prod-dm2-011-sb.servicebus.windows.net",
        "g73-prod-dm2-011-sb.servicebus.windows.net",
        "g74-prod-dm2-011-sb.servicebus.windows.net",
        "g75-prod-dm2-011-sb.servicebus.windows.net",
        "g76-prod-dm2-011-sb.servicebus.windows.net",
        "g77-prod-dm2-011-sb.servicebus.windows.net",
        "g78-prod-dm2-011-sb.servicebus.windows.net",
        "g79-prod-dm2-011-sb.servicebus.windows.net",
        "g80-prod-dm2-011-sb.servicebus.windows.net",
        "g81-prod-dm2-011-sb.servicebus.windows.net",
        "g82-prod-dm2-011-sb.servicebus.windows.net",
        "g83-prod-dm2-011-sb.servicebus.windows.net",
        "g84-prod-dm2-011-sb.servicebus.windows.net",
        "g85-prod-dm2-011-sb.servicebus.windows.net",
        "g86-prod-dm2-011-sb.servicebus.windows.net",
        "g87-prod-dm2-011-sb.servicebus.windows.net",
        "g88-prod-dm2-011-sb.servicebus.windows.net",
        "g89-prod-dm2-011-sb.servicebus.windows.net",
        "g90-prod-dm2-011-sb.servicebus.windows.net",
        "g91-prod-dm2-011-sb.servicebus.windows.net",
        "g92-prod-dm2-011-sb.servicebus.windows.net",
        "g93-prod-dm2-011-sb.servicebus.windows.net",
        "g94-prod-dm2-011-sb.servicebus.windows.net",
        "g95-prod-dm2-011-sb.servicebus.windows.net",
        "g96-prod-dm2-011-sb.servicebus.windows.net",
        "g97-prod-dm2-011-sb.servicebus.windows.net",
        "g98-prod-dm2-011-sb.servicebus.windows.net",
        "g99-prod-dm2-011-sb.servicebus.windows.net",
        "g100-prod-dm2-011-sb.servicebus.windows.net",
        "g101-prod-dm2-011-sb.servicebus.windows.net",
        "g102-prod-dm2-011-sb.servicebus.windows.net",
        "g103-prod-dm2-011-sb.servicebus.windows.net",
        "g104-prod-dm2-011-sb.servicebus.windows.net",
        "g105-prod-dm2-011-sb.servicebus.windows.net",
        "g106-prod-dm2-011-sb.servicebus.windows.net",
        "g107-prod-dm2-011-sb.servicebus.windows.net",
        "g108-prod-dm2-011-sb.servicebus.windows.net",
        "g109-prod-dm2-011-sb.servicebus.windows.net",
        "g110-prod-dm2-011-sb.servicebus.windows.net",
        "g111-prod-dm2-011-sb.servicebus.windows.net",
        "g112-prod-dm2-011-sb.servicebus.windows.net",
        "g113-prod-dm2-011-sb.servicebus.windows.net",
        "g114-prod-dm2-011-sb.servicebus.windows.net",
        "g115-prod-dm2-011-sb.servicebus.windows.net",
        "g116-prod-dm2-011-sb.servicebus.windows.net",
        "g117-prod-dm2-011-sb.servicebus.windows.net",
        "g118-prod-dm2-011-sb.servicebus.windows.net",
        "g119-prod-dm2-011-sb.servicebus.windows.net",
        "g120-prod-dm2-011-sb.servicebus.windows.net",
        "g121-prod-dm2-011-sb.servicebus.windows.net",
        "g122-prod-dm2-011-sb.servicebus.windows.net",
        "g123-prod-dm2-011-sb.servicebus.windows.net",
        "g124-prod-dm2-011-sb.servicebus.windows.net",
        "g125-prod-dm2-011-sb.servicebus.windows.net",
        "g126-prod-dm2-011-sb.servicebus.windows.net",
        "g127-prod-dm2-011-sb.servicebus.windows.net",
        "amsprodcu-12-s.servicebus.windows.net",
        "g0-prod-bl3-011-sb.servicebus.windows.net",
        "g1-prod-bl3-011-sb.servicebus.windows.net",
        "g2-prod-bl3-011-sb.servicebus.windows.net",
        "g3-prod-bl3-011-sb.servicebus.windows.net",
        "g4-prod-bl3-011-sb.servicebus.windows.net",
        "g5-prod-bl3-011-sb.servicebus.windows.net",
        "g6-prod-bl3-011-sb.servicebus.windows.net",
        "g7-prod-bl3-011-sb.servicebus.windows.net",
        "g8-prod-bl3-011-sb.servicebus.windows.net",
        "g9-prod-bl3-011-sb.servicebus.windows.net",
        "g10-prod-bl3-011-sb.servicebus.windows.net",
        "g11-prod-bl3-011-sb.servicebus.windows.net",
        "g12-prod-bl3-011-sb.servicebus.windows.net",
        "g13-prod-bl3-011-sb.servicebus.windows.net",
        "g14-prod-bl3-011-sb.servicebus.windows.net",
        "g15-prod-bl3-011-sb.servicebus.windows.net",
        "g16-prod-bl3-011-sb.servicebus.windows.net",
        "g17-prod-bl3-011-sb.servicebus.windows.net",
        "g18-prod-bl3-011-sb.servicebus.windows.net",
        "g19-prod-bl3-011-sb.servicebus.windows.net",
        "g20-prod-bl3-011-sb.servicebus.windows.net",
        "g21-prod-bl3-011-sb.servicebus.windows.net",
        "g22-prod-bl3-011-sb.servicebus.windows.net",
        "g23-prod-bl3-011-sb.servicebus.windows.net",
        "g24-prod-bl3-011-sb.servicebus.windows.net",
        "g25-prod-bl3-011-sb.servicebus.windows.net",
        "g26-prod-bl3-011-sb.servicebus.windows.net",
        "g27-prod-bl3-011-sb.servicebus.windows.net",
        "g28-prod-bl3-011-sb.servicebus.windows.net",
        "g29-prod-bl3-011-sb.servicebus.windows.net",
        "g30-prod-bl3-011-sb.servicebus.windows.net",
        "g31-prod-bl3-011-sb.servicebus.windows.net",
        "g32-prod-bl3-011-sb.servicebus.windows.net",
        "g33-prod-bl3-011-sb.servicebus.windows.net",
        "g34-prod-bl3-011-sb.servicebus.windows.net",
        "g35-prod-bl3-011-sb.servicebus.windows.net",
        "g36-prod-bl3-011-sb.servicebus.windows.net",
        "g37-prod-bl3-011-sb.servicebus.windows.net",
        "g38-prod-bl3-011-sb.servicebus.windows.net",
        "g39-prod-bl3-011-sb.servicebus.windows.net",
        "g40-prod-bl3-011-sb.servicebus.windows.net",
        "g41-prod-bl3-011-sb.servicebus.windows.net",
        "g42-prod-bl3-011-sb.servicebus.windows.net",
        "g43-prod-bl3-011-sb.servicebus.windows.net",
        "g44-prod-bl3-011-sb.servicebus.windows.net",
        "g45-prod-bl3-011-sb.servicebus.windows.net",
        "g46-prod-bl3-011-sb.servicebus.windows.net",
        "g47-prod-bl3-011-sb.servicebus.windows.net",
        "g48-prod-bl3-011-sb.servicebus.windows.net",
        "g49-prod-bl3-011-sb.servicebus.windows.net",
        "g50-prod-bl3-011-sb.servicebus.windows.net",
        "g51-prod-bl3-011-sb.servicebus.windows.net",
        "g52-prod-bl3-011-sb.servicebus.windows.net",
        "g53-prod-bl3-011-sb.servicebus.windows.net",
        "g54-prod-bl3-011-sb.servicebus.windows.net",
        "g55-prod-bl3-011-sb.servicebus.windows.net",
        "g56-prod-bl3-011-sb.servicebus.windows.net",
        "g57-prod-bl3-011-sb.servicebus.windows.net",
        "g58-prod-bl3-011-sb.servicebus.windows.net",
        "g59-prod-bl3-011-sb.servicebus.windows.net",
        "g60-prod-bl3-011-sb.servicebus.windows.net",
        "g61-prod-bl3-011-sb.servicebus.windows.net",
        "g62-prod-bl3-011-sb.servicebus.windows.net",
        "g63-prod-bl3-011-sb.servicebus.windows.net",
        "g64-prod-bl3-011-sb.servicebus.windows.net",
        "g65-prod-bl3-011-sb.servicebus.windows.net",
        "g66-prod-bl3-011-sb.servicebus.windows.net",
        "g67-prod-bl3-011-sb.servicebus.windows.net",
        "g68-prod-bl3-011-sb.servicebus.windows.net",
        "g69-prod-bl3-011-sb.servicebus.windows.net",
        "g70-prod-bl3-011-sb.servicebus.windows.net",
        "g71-prod-bl3-011-sb.servicebus.windows.net",
        "g72-prod-bl3-011-sb.servicebus.windows.net",
        "g73-prod-bl3-011-sb.servicebus.windows.net",
        "g74-prod-bl3-011-sb.servicebus.windows.net",
        "g75-prod-bl3-011-sb.servicebus.windows.net",
        "g76-prod-bl3-011-sb.servicebus.windows.net",
        "g77-prod-bl3-011-sb.servicebus.windows.net",
        "g78-prod-bl3-011-sb.servicebus.windows.net",
        "g79-prod-bl3-011-sb.servicebus.windows.net",
        "g80-prod-bl3-011-sb.servicebus.windows.net",
        "g81-prod-bl3-011-sb.servicebus.windows.net",
        "g82-prod-bl3-011-sb.servicebus.windows.net",
        "g83-prod-bl3-011-sb.servicebus.windows.net",
        "g84-prod-bl3-011-sb.servicebus.windows.net",
        "g85-prod-bl3-011-sb.servicebus.windows.net",
        "g86-prod-bl3-011-sb.servicebus.windows.net",
        "g87-prod-bl3-011-sb.servicebus.windows.net",
        "g88-prod-bl3-011-sb.servicebus.windows.net",
        "g89-prod-bl3-011-sb.servicebus.windows.net",
        "g90-prod-bl3-011-sb.servicebus.windows.net",
        "g91-prod-bl3-011-sb.servicebus.windows.net",
        "g92-prod-bl3-011-sb.servicebus.windows.net",
        "g93-prod-bl3-011-sb.servicebus.windows.net",
        "g94-prod-bl3-011-sb.servicebus.windows.net",
        "g95-prod-bl3-011-sb.servicebus.windows.net",
        "g96-prod-bl3-011-sb.servicebus.windows.net",
        "g97-prod-bl3-011-sb.servicebus.windows.net",
        "g98-prod-bl3-011-sb.servicebus.windows.net",
        "g99-prod-bl3-011-sb.servicebus.windows.net",
        "g100-prod-bl3-011-sb.servicebus.windows.net",
        "g101-prod-bl3-011-sb.servicebus.windows.net",
        "g102-prod-bl3-011-sb.servicebus.windows.net",
        "g103-prod-bl3-011-sb.servicebus.windows.net",
        "g104-prod-bl3-011-sb.servicebus.windows.net",
        "g105-prod-bl3-011-sb.servicebus.windows.net",
        "g106-prod-bl3-011-sb.servicebus.windows.net",
        "g107-prod-bl3-011-sb.servicebus.windows.net",
        "g108-prod-bl3-011-sb.servicebus.windows.net",
        "g109-prod-bl3-011-sb.servicebus.windows.net",
        "g110-prod-bl3-011-sb.servicebus.windows.net",
        "g111-prod-bl3-011-sb.servicebus.windows.net",
        "g112-prod-bl3-011-sb.servicebus.windows.net",
        "g113-prod-bl3-011-sb.servicebus.windows.net",
        "g114-prod-bl3-011-sb.servicebus.windows.net",
        "g115-prod-bl3-011-sb.servicebus.windows.net",
        "g116-prod-bl3-011-sb.servicebus.windows.net",
        "g117-prod-bl3-011-sb.servicebus.windows.net",
        "g118-prod-bl3-011-sb.servicebus.windows.net",
        "g119-prod-bl3-011-sb.servicebus.windows.net",
        "g120-prod-bl3-011-sb.servicebus.windows.net",
        "g121-prod-bl3-011-sb.servicebus.windows.net",
        "g122-prod-bl3-011-sb.servicebus.windows.net",
        "g123-prod-bl3-011-sb.servicebus.windows.net",
        "g124-prod-bl3-011-sb.servicebus.windows.net",
        "g125-prod-bl3-011-sb.servicebus.windows.net",
        "g126-prod-bl3-011-sb.servicebus.windows.net",
        "g127-prod-bl3-011-sb.servicebus.windows.net"
      ],`

**Comment by live1206** [comment]
@musukwamoshi Thank you for getting the data!
`g125-prod-bl3-011-sb.servicebus.windows.net` is not a valid Uri for System.Uri.
If we try new Uri("g125-prod-bl3-011-sb.servicebus.windows.net"), it will throw `Invalid URI: The format of the URI could not be determined. ` It expects the Url to include scheme or it's a system file path.

**Comment by musukwamoshi** [comment]
@live1206  No problem. I'm glad I could be of help!

**Comment by live1206** [comment]
Will be fixed in next release version.
