### ISSUE TITLE
502 Bad Gate Way issues

### ISSUE THREAD

**Issue by MarvinWenS** [Azure/azure-rest-api-specs-examples#3381]
### Link to sample

https://learn.microsoft.com/zh-cn/rest/api/aks/managed-clusters/abort-latest-operation?tabs=HTTP

### Library name and version

azure-mgmt-containerservice 26.0.0

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [X] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [ ] Sample not working
- [ ] Sample missing
- [x] Do not understand sample

### Issue details

Hi team,
     Why it is report me 502 Bad GateWay error, while I use agent pool and manager cluster begin_abort_latest_operation method? When I request using the rest API, when it is an update, the error code reported to me for the first request. If I request again, he will report me that the current status is' cancel 'and' operation not allowed '.
   Python SDK request code:
      

> client.managed_clusters.begin_abort_latest_operation(resource_group_name=self.resource_group,
                                                              resource_name=self.cluster_name)

> client.agent_pools.begin_abort_latest_operation(self.resource_group, self.cluster_name, nodepool_name)

   API request details:
   POST: /subscriptions/af8a838e-eb6b-4a7a-974e-36128b1ea4b7/resourceGroups/cqfybg6fef-sapsecxco2-d7/providers/Microsoft.ContainerService/managedclusters/cqfybg6fef-sapsecxco2-d7-kub/abort?api-version=2023-07-01
   POST: /subscriptions/af8a838e-eb6b-4a7a-974e-36128b1ea4b7/resourceGroups/cqfybg6fef-sapsecxco2-d7/providers/Microsoft.ContainerService/managedClusters/cqfybg6fef-sapsecxco2-d7-kub/agentPools/shrvsbzqv9/abort?api-version=2021-09-01
BR
Marvin,Wen

**Comment by ChenxiJiang333** [comment]
Hi, @MarvinWenS 
If you got the response `Cancel operation is not allowed when the ProvisioningState is Canceled`, it means that the last long operation was successfully aborted. Your first request was processed by the service, but the client didn't receive the response correctly, so it came to `502 Bad GateWay` error.
Usually the response would be in 204 status with no content returned. Please retry the method and if this error code keeping reported, please give us feedback and provide more details on the reproduction steps.
