### ISSUE TITLE
[Sample Issue]

### ISSUE THREAD

**Issue by NavidMitchell** [Azure/azure-rest-api-specs-examples#3427]
### Link to sample

https://learn.microsoft.com/en-us/rest/api/backup/backup-jobs/list?tabs=JavaScript#list-jobs-with-time-filter

### Library name and version

@azure/arm-recoveryservicesbackup 11.0.0

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [X] JavaScript/TypedScript
- [ ] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [X] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

The filter example provided does not filter the data. I have tried this on my Azure environment and I always get back all JobResource records regardless of the date filter I provide. 

### Expected behavior

The list of JobResource records filtered by date.

### Actual behavior

All records are returned.

### Reproduction Steps

Run sample with dates correct for your environment. 

### Environment

Node 18.15.0 
OSX 14.0

**Comment by MaryGao** [comment]
@kazrael2119 Could you take a look at this issue?

**Comment by kazrael2119** [comment]
Hi @NavidMitchell ,could you give your code, and your screenshot of the backup Jobs on portal? I can use the filter to list jobs.

**Comment by kazrael2119** [comment]
close this issue as there has been no response for a long time. please create a new issue if necessary. Thanks
