### ISSUE TITLE
[Python] AttributeError: 'CognitiveServicesManagementClient' object has no attribute 'deployments'

### ISSUE THREAD

**Issue by plaksnor** [Azure/azure-rest-api-specs-examples#4068]
### Link to sample

https://learn.microsoft.com/en-us/rest/api/cognitiveservices/accountmanagement/deployments/list?view=rest-cognitiveservices-accountmanagement-2023-05-01&tabs=Python

### Library name and version

azure-mgmt-cognitiveservices==13.5.0

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [X] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [X] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

This part of the code:
```
deployment = cognitiveservices_client.deployments.begin_create_or_update(
    resource_group_name = resource_group_name,
    account_name = account_name,
    deployment_name = "chat",
    deployment = {
        "properties": {"model": {"format": "OpenAI", "name": "ada", "version": "1"}},
        "sku": {"capacity": 1, "name": "Standard"},
    },
)
```
results in this error:
```
AttributeError: 'CognitiveServicesManagementClient' object has no attribute 'deployments'
```

### Expected behavior

I expect this code to create a deployment in the Azure OpenAI account. Creating deployments manually in the Azure Portal by using Azure AI Studio works without any problems.

### Actual behavior

Not creating any deployments within the OpenAI account.

### Reproduction Steps

Create an account like this:
```
from azure.mgmt.cognitiveservices import CognitiveServicesManagementClient

cognitiveservices_client = CognitiveServicesManagementClient(
    credential=credential,
    subscription_id=subscription_id
)

account_name = "anyname12345"

account = cognitiveservices_client.accounts.create(
    resource_group_name,
    account_name,
    {
      "location": "West Europe",
      "kind": "OpenAI",
      "sku": {
        "name": "S0"
      },
      "identity": {
        "type": "SystemAssigned"
      }
    }
)
print("Created OpenAI account:\n{}".format(account))
```
This should work and should output something like this:
```
Created OpenAI account:
{'additional_properties': {}, 'etag': '"200035e7-0000-0d00-0000-65a30a020000"', 'id': '/subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.CognitiveServices/accounts/<account_name>', 'kind': 'OpenAI', 'location': 'West Europe', 'name': '<account_name>', 'properties': <azure.mgmt.cognitiveservices.models._models_py3.CognitiveServicesAccountProperties object at 0x7fc63c41fc10>, 'sku': <azure.mgmt.cognitiveservices.models._models_py3.Sku object at 0x7fc63c41fdf0>, 'tags': None, 'type': 'Microsoft.CognitiveServices/accounts', 'identity': <azure.mgmt.cognitiveservices.models._models_py3.Identity object at 0x7fc63c41f2b0>}
```

Now try to get a list of deployments or create a deployment with that same cognitiveservices_client object:

```
    response = cognitiveservices_client.deployments.list(
        resource_group_name=resource_group_name,
        account_name=account_name
    )
```
or
```
deployment = cognitiveservices_client.deployments.begin_create_or_update(
    resource_group_name = resource_group_name,
    account_name = account_name,
    deployment_name = "chat",
    deployment = {
        "properties": {"model": {"format": "OpenAI", "name": "ada", "version": "1"}},
        "sku": {"capacity": 1, "name": "Standard"}
    }
)
print(deployment)
```

This should cause an error.

### Environment

Authenticating as follows:
```
!az login --tenant $AZURE_TENANT --use-device-code --output none
from azure.identity import AzureCliCredential
credential = AzureCliCredential()
```

Using the following Python packages:
azure-mgmt-cognitiveservices==13.5.0

Python version: 3.8.18
JupyterLab version 3.4.4
```[tasklist]
### Similar
- [ ] https://github.com/openai/openai-python/issues/457
```

**Comment by plaksnor** [comment]
I used this as a workaround, but according the link below the openai library no longer has support for creating deployments (or it's the other way around: the cognitive services no longer supports model deployments).
[https://github.com/openai/openai-python/issues/457](https://github.com/openai/openai-python/issues/457)
```
import openai

# Manually get the API key first from the Azure Portal
openai.api_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
openai.api_type = "azure"
openai.api_version = "2023-03-15-preview"
openai.api_base = account.properties.endpoint

model = "gpt-35-turbo"
print(f'Creating a new deployment with model: {model}')
result = openai.Deployment.create(model=model, scale_settings={"scale_type":"standard"})

deployment_id = result["id"]
print(f'Successfully created deployment with id: {deployment_id}')
```

**Comment by ChenxiJiang333** [comment]
Hi @plaksnor 
I have done these steps but cannot reproduce the error. It seems there's something wrong with the local package you're using. Please rechecking the current python interpreter and force reinstall the package and try.
![image](https://github.com/Azure/azure-rest-api-specs-examples/assets/119990644/ef71a531-8ec0-4899-8802-fc94532e3791)

**Comment by plaksnor** [comment]
Thanks @ChenxiJiang333! Managed to update to a workable version of CognitiveServicesManagementClient.
First tried 
```
pip install azure-mgmt-cognitiveservices --upgrade
```
...which didn't make any difference. Then I used...
```
pip install azure-mgmt-cognitiveservices --force --upgrade
```
...which caused an openssl error:
```
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168
```
Since I'm not able to install/update Python with a newer version of OpenSSL, I had to go back to an older version, so I ran:
```
pip install urllib3==1.26.15
```
..and that made it all work (after restarting the kernel a couple of times. It's a lot trial and error).

So I'm using these versions right now:
```
pip freeze | grep 'azure-identity\|azure-mgmt-cognitiveservices\|urllib3'
```
azure-mgmt-cognitiveservices==13.5.0
urllib3==1.26.15
